### ISSUE TITLE
Faction H & Faction A

### ISSUE THREAD

**Issue by DarkBrain2580** [Faq/Truice#57]
With the latest Trinitycore rev is only One faction table in the database.

Look here: https://github.com/TrinityCore/TrinityCore/commit/c536305e3a3c4f41e94d14fae73ba7a2d8d13be2

**Comment by Faq** [comment]
Hello,
This is new and updated tool, please use it in feature:
Keira2 by Helias and Shin https://community.trinitycore.org/topic/11397-keira2-the-trinitycore-database-web-editor-cross-platform/
Some more updated Truice by chaosua https://community.trinitycore.org/topic/7639-bin-truice-win32/
