### ISSUE TITLE
Truice fix

### ISSUE THREAD

**Issue by tiikerikissa** [Faq/Truice#58]
Hello! 

t we all need some fix please chnage some tabel i give example:

gameobject_queststarter need change this gameobject_involvedrelation

gameobject_questender needchange this gameobject_questrelation

and creature table is

creature_queststarter need change this creature_involvedrelation

creature_questender need change this creature_questrelation

now we can use this mist of pandaria repack 

100% this works 

bestregards github tiikerikissa

**Comment by Faq** [comment]
Hello,
This is new and updated tool, please use it in feature:
Keira2 by Helias and Shin https://community.trinitycore.org/topic/11397-keira2-the-trinitycore-database-web-editor-cross-platform/
Some more updated Truice by chaosua https://community.trinitycore.org/topic/7639-bin-truice-win32/
