### ISSUE TITLE
Truice Not Reachable

### ISSUE THREAD

**Issue by alexandre433** [Faq/Truice#59]
Hi,

The link to the truice for trinitycore is not working.
Please Fix the link or arrange another one.

Thank You In Advance

**Comment by Faq** [comment]
Hello, 
This is new and updated tool, please use it in feature: 
Keira2 by Helias and Shin https://community.trinitycore.org/topic/11397-keira2-the-trinitycore-database-web-editor-cross-platform/
Some more updated Truice by chaosua https://community.trinitycore.org/topic/7639-bin-truice-win32/
