### ISSUE TITLE
OfferRewardText & RequestItemText

### ISSUE THREAD

**Issue by Hyakkimaru** [Faq/Truice#60]
Hi, I'm really happy to see a new update on Truice ! It was the most useful tool for lazy dev like me :D !

I report you something : Even if we fill OfferRewardText & RequestItemText, values don't appear in the generated script, which means it's always empty after executing request. :( 

Issue 2 : Truice can't generate locales script (in quest) and we can't insert our locales in DB with it. (in my case, it's frFR)

Thank you for the uptade, you save me from using keira !

**Comment by Faq** [comment]
Please split issues, so it is only 1 per ticket.

**Comment by Hyakkimaru** [comment]
Ok I make a new issue !

**Comment by Hyakkimaru** [comment]
Sorry ! Didn't saw the P.s !

Yes, Quest_template isn't updated as far I remember.

It's a question of comfort too, I always preferred truice, much more practical imo

**Comment by grimgravy** [comment]
The Truice is much better than the keira, because it is a simple program to download and does not have features like keira.
Finally be continuing

**Comment by Faq** [comment]
Please check with Truice_v2.1.0b and report back.

**Comment by Faq** [comment]
or just with latest v2.1.0c

**Comment by peycho** [comment]
Thank you @Faq for the updates.

**Comment by OlegVintage88** [comment]
Thanks, now works. But when you choose the quest, the text of the columns is not displayed OfferRewardText & RequestItemText. 
Screenshot.
[http://i103.fastpic.ru/big/2018/0114/12/c70dd24e4d8269420ef3586a55526212.jpg](url)

If you select other values in the tab (Quest part 2) error
Screenshot.
http://i102.fastpic.ru/big/2018/0114/60/8ca58c7cdab4a9b8c487046181a1e660.jpg
