### ISSUE TITLE
Application hangs

### ISSUE THREAD

**Issue by OlegVintage88** [Faq/Truice#62]
When pressed, the application hangs

http://i103.fastpic.ru/big/2018/0114/d6/2631a075023f417e596acfc65069cad6.jpg
http://i102.fastpic.ru/big/2018/0114/74/805a7d220a4bba42fc0a1eb18e5e7074.jpg

**Comment by Faq** [comment]
Strange, for me opens fine.
Try quest id 1149, it has in db SourceSpellID

**Comment by OlegVintage88** [comment]
Also hangs (
Perhaps this is something like that http://i100.fastpic.ru/big/2018/0115/94/7908e8a8c01520e4fbe0bbaf46d80394.jpg
