### ISSUE TITLE
Please add needed .dll's for this app

### ISSUE THREAD

**Issue by Reforge-Mark** [Faq/Truice#64]
the Released versions of this application can not work without proper .dll's
please provide: 
Functionlib.dll
libeay32.dll
libmysql.dll
and other needed .dll's
the application asks for mysql .dll's and can not seem to locate them, even though i have mysql installed
https://prnt.sc/ji6zbn

**Comment by Faq** [comment]
libmysql is here https://github.com/Faq/Truice/releases/tag/v2.1.1 other not needed.

What framework version you have installed? what os? w32 or 64bit

**Comment by Reforge-Mark** [comment]
windows 7 here on my laptop that im using atm. 64bit, at home I have windows 10 also 64bit. 
Ahh, now I see what is the issue. It is my mistake..
Have just downloaded the pre-release 2.1.1b  it has no dll inside nor other things that actual release 2.1.1 has.
2.1.1  works fine :)

**Comment by Faq** [comment]
so issue closed :)
