### ISSUE TITLE
Redefined action SMART_ACTION_STOP_MOTION -> SMART_ACTION_REMOVE_MOVEMENT

### ISSUE THREAD

**Issue by ccrs** [Faq/Truice#66]
https://github.com/TrinityCore/TrinityCore/commit/982643cd96790ffc54e7a3e507469649f3b074d2#diff-7644387f3507b6763048646e59512f28R1125
https://github.com/TrinityCore/TrinityCore/commit/982643cd96790ffc54e7a3e507469649f3b074d2#diff-55afa6409f4613551dd9ea30b26e4cdaR2241

"Tries to remove the first found movement with the given ``movementType``, ``forced`` flags the use of ``Unit::StopMoving``"

**Comment by Faq** [comment]
https://github.com/Faq/Truice/releases/tag/v2.1.2
