### ISSUE TITLE
Missing changes

### ISSUE THREAD

**Issue by ccrs** [Faq/Truice#67]
A. https://github.com/TrinityCore/TrinityCore/commit/7c5b69d18bb315d369bf0bbfc16b795d63d0f73c
B. https://github.com/TrinityCore/TrinityCore/commit/5ad38c31b0ed633555f281318684e57ea5d6dd73
C. https://github.com/TrinityCore/TrinityCore/commit/592516ae69d89da3bcb0ede144644a3d2e0186e0#diff-3bb6433b3e013a0dcc2f5e532eb3a748R1

**Comment by ccrs** [comment]
https://github.com/TrinityCore/TrinityCore/commit/37995ade2991ed27845728eb6a6dd95f3a490849
https://github.com/TrinityCore/TrinityCore/commit/619a5534c5f6ce5e736b22e645f7bac72eba9b16
https://github.com/TrinityCore/TrinityCore/commit/f913f3bb8977c127d200d5d4a608ab434b21bbcd

**Comment by Faq** [comment]
C. left
