### ISSUE TITLE
UI: Searcher not working

### ISSUE THREAD

**Issue by ccrs** [Faq/Truice#71]
On tab SmartAI, ```event_type``` ```action_type``` ```target_type``` do not show anything on search/lookup

Using 2.1.3

**Comment by ccrs** [comment]
```event_flags``` shows some column from creature_template, ```unit_flags``` maybe

**Comment by ccrs** [comment]
```source_type``` shows nothing

**Comment by Faq** [comment]
Search is working just fine, there are 2 ways:
1. search npc and then go to "SmartAI" and use button there "Goto SmartAI" what will load maina "SmartAI" tab.
2. Go to main "SmartAI" tab and put entry (example 30657) in "Entry or GUID" and use "Load" button.

event_flags was not working correctly as missing 2 entries, https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130108/smart+scripts#smart_scripts-event_flags

**Comment by ccrs** [comment]
this is what I meant

![image](https://user-images.githubusercontent.com/4329612/44594254-eceab200-a7c5-11e8-89c5-afdb34961f31.png)
![image](https://user-images.githubusercontent.com/4329612/44594268-f70cb080-a7c5-11e8-8ed8-6d3c6d7fed00.png)

**Comment by ccrs** [comment]
oooh I see, you have to move it outside, my bad

**Comment by Faq** [comment]
Im wondering how you got that "SAI_EventFlags" window in that view (first pic).

**Comment by Faq** [comment]
a I see, if exe and dll is still in one folder then thats happening :)

**Comment by ccrs** [comment]
managed to compile the latest commit on Embarcadero Community Edition, working nicely 👍

**Comment by Faq** [comment]
Good, didnt test it myself. Good that they released it 1month ago, now more community can get in.
