### ISSUE TITLE
Empty forms

### ISSUE THREAD

**Issue by Hobbilis** [Faq/Truice#75]
SAI_EventType,
SAI_ActionType,
source_type,
target_type
all these forms are empty. It is not possible to pick anything.

**Comment by Faq** [comment]
what trinity revision and what truice version?

**Comment by Hobbilis** [comment]
TC rev: https://github.com/TrinityCore/TrinityCore/commit/72efd59ccc724c37ed805b73270b00f6771acdc7
Truice ver: 2.1.3

**Comment by Faq** [comment]
its the same as #74

**Comment by Hobbilis** [comment]
All these forms are still empty in 2.1.4 version

**Comment by Faq** [comment]
example id?

**Comment by Hobbilis** [comment]
I'm talking about Search forms.
Forms where it should be possible to pick something from a list.
I took screenshort to compare what Truice is showing and what Discover's SAI Editor is showing
![exampleevent](https://user-images.githubusercontent.com/4030038/47105188-8624ca80-d243-11e8-97d0-035355b60c92.jpg)
![exampleaction](https://user-images.githubusercontent.com/4030038/47105189-8624ca80-d243-11e8-83d7-b9aa7cc38877.jpg)

**Comment by Faq** [comment]
finally I see what you mean ...

**Comment by Faq** [comment]
Read how to run: https://github.com/Faq/Truice/blob/master/Readme.md
works for me

**Comment by Hobbilis** [comment]
Oh, thanks! 👍
