### ISSUE TITLE
Creature_text editing

### ISSUE THREAD

**Issue by Hobbilis** [Faq/Truice#76]
Under Creature tab, add another sub-tab for viewing/editing it's creature_text table

**Comment by Faq** [comment]
thats a suggestion? Something is wrong with that sentence. Google translate?

**Comment by Hobbilis** [comment]
Yeah it was a suggestion. No, I am not using google translate.
Please consider adding creature_text tab so that we can modify it's respective content in Truice.

**Comment by Faq** [comment]
Planned release till end of weekend.

**Comment by Hobbilis** [comment]
Thanks, it will be a pretty good feature.
