### ISSUE TITLE
Checkbox forms

### ISSUE THREAD

**Issue by Hobbilis** [Faq/Truice#77]
Checkbox forms display same options for different fields.
For example in Quest tab, Quest part1 -> QuestFlags has following checkbox options
![questflags](https://user-images.githubusercontent.com/4030038/47084399-ab014980-d213-11e8-80b2-e17e485e34fe.jpg)

Which is wrong, all the flags are listed in the TC wiki
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130261/quest+template#quest_template-Flags

And then AllowableRaces, for example, have same checkbox form with same options
![allowableraces](https://user-images.githubusercontent.com/4030038/47084603-3e3a7f00-d214-11e8-8048-45e9186d5964.jpg)

**Comment by Faq** [comment]
Read how to run: https://github.com/Faq/Truice/blob/master/Readme.md
works for me
