### ISSUE TITLE
Quest tab error

### ISSUE THREAD

**Issue by Hobbilis** [Faq/Truice#78]
When you double click a quest from a search list it takes you to "Quest Part 1" tab
Following error appears
![questerror](https://user-images.githubusercontent.com/4030038/47145357-d47cac80-d2c9-11e8-8268-af7deecce179.jpg)

Also, a small typo for "Quest Tenders" tab. Should be saying "Quest Enders"

**Comment by Faq** [comment]
OfferRewardText, RequestItemsText was removed from quest_template_locale in recent comits, looking wich one is it.

**Comment by Faq** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2f5403d4af3a90a6e51a377e05a55a0d197afb4d

**Comment by Hobbilis** [comment]
I figured, but I still wanted to point the error.

**Comment by Hobbilis** [comment]
Don't know why, it was working fine earlier
But this is happening when selecting SmartAI as well
![smartaierror](https://user-images.githubusercontent.com/4030038/47233525-5c021280-d3d3-11e8-935c-3cc75053600d.jpg)

**Comment by Faq** [comment]
@Hobbilis test with https://github.com/Faq/Truice/releases/tag/v2.1.4a and give feedback.

**Comment by Hobbilis** [comment]
No errors so far, will report if anything pops up. Thanks for the update, appreciated.

**Comment by Faq** [comment]
quest locale tab shows correct info? was able nt test that as all time showed only ruRU

**Comment by Faq** [comment]
closing this, will work on Locales Quest tab when someone actually will report that and use it. It was like that for ages :)
