### ISSUE TITLE
SmartAI result missing script entries related to SAI calling the script

### ISSUE THREAD

**Issue by Hobbilis** [Faq/Truice#79]
When I select, for example, NPC entry: 33589 and click on SmartAI tab it loads his SmartAI table, but it would be good if it could load his scripts as well.
Here is what I mean by that. This npc (33589) has 4 SmartAI entries, but if you go into the DB and check he actually has 9 rows. In the picture below I have highlighted the 4 rows that Truice is displaying, however the 5 other rows of scripts which are linked to this npc are not being shown. I suggest implementing that feature as well. All the scripts use the TC standard of entryorguid*100 to determine its respective entryorguid id, like how it is displayed in the picture below
![saisuggestion](https://user-images.githubusercontent.com/4030038/47269083-94cbf400-d559-11e8-9820-18327146c28c.jpg)

Also, that small arrow I drew pointing to the text overlapping. Maybe it's better to put that text into tooltip?

**Comment by Hobbilis** [comment]
Actually, this is not even an issue. You can find all of the related scripts by just typing in entryorguid and changing source_type.
But that text overlapping could be fixed though.

**Comment by Faq** [comment]
hmm didn't found such entryorguid you showed=3358900. Custom stuff?

**Comment by Hobbilis** [comment]
No, straight from a fresh DB install.
