### ISSUE TITLE
Cannot load vendor library

### ISSUE THREAD

**Issue by peycho** [Faq/Truice#85]
I have some weird issue on a fresh installed Windows 10 / 64b

I installed Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 and MySQL - I suspect that this was required as well.
I have MySQL Workbech working. I also installed some additional MySQL connectors. I'm able to connect to the mysql server with no issues, but I get this error when I try to connect with Truice:

![dll_error](https://user-images.githubusercontent.com/170853/79065167-d7860c80-7cb6-11ea-85ab-3ce80f27411d.jpg)

The server is not on my host, It's hosted on external Linux server.

Do I need some additional software to install to make this works?
I apologize in advance. I'm not Windows user and I kinda feel lost.

Thanks.

**Comment by Faq** [comment]
HI, it needs MySQL v5.7.23, but I'm not updating t for long time. 
You can try use https://github.com/Rushor/SAI-Editor

**Comment by Faq** [comment]
it is updated editor

**Comment by peycho** [comment]
I've managed to fix the problem.
I updated the application compatibility to work as Windows 7 and now it works.

Thanks.
